services:
  gateway:
    build: .
    container_name: signlingo-gateway
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - signlingo-mesh

networks:
  signlingo-mesh:
    external: true
